10.5

diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test000-rootdse b/OpenLDAP/OpenLDAP/tests/scripts/test000-rootdse
--- a/OpenLDAP/OpenLDAP/tests/scripts/test000-rootdse
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test000-rootdse
@@ -1,45 +1,39 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test000-rootdse,v 1.9.2.5 2002/09/24 00:05:01 kurt Exp $
-
-SRCDIR="."
-if test $# -ge 1 ; then
-	SRCDIR=$1; shift
-fi
-BACKEND=bdb
-if test $# -ge 1 ; then
-	BACKEND=$1; shift
-fi
-MONITORDB=no
-if test $# -ge 1 ; then
-	MONITORDB=$1; shift
-fi
-
-WAIT=0
-if test $# -ge 1 ; then
-	WAIT=1; shift
-fi
+# $OpenLDAP: pkg/ldap/tests/scripts/test000-rootdse,v 1.22.2.5 2006/01/03 22:16:28 kurt Exp $
+## This work is part of OpenLDAP Software <http://www.openldap.org/>.
+##
+## Copyright 1998-2006 The OpenLDAP Foundation.
+## All rights reserved.
+##
+## Redistribution and use in source and binary forms, with or without
+## modification, are permitted only as authorized by the OpenLDAP
+## Public License.
+##
+## A copy of this license is available in the file LICENSE in the
+## top-level directory of the distribution or, alternatively, at
+## <http://www.OpenLDAP.org/license.html>.
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
-echo "Datadir is $DATADIR"
+mkdir -p $TESTDIR $DBDIR1
 
-echo "Cleaning up in $DBDIR..."
-
-rm -f $DBDIR/[!C]*
-
-echo "Starting slapd on TCP/IP port $PORT..."
-. $CONFFILTER $BACKEND $MONITORDB < $SCHEMACONF > $DBCONF
-$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
+echo "Starting slapd on TCP/IP port $PORT1..."
+. $CONFFILTER $BACKEND $MONITORDB < $SCHEMACONF > $CONF1
+$SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
     echo PID $PID
     read foo
 fi
+KILLPIDS="$PID"
+
+sleep 1
 
 echo "Using ldapsearch to retrieve the root DSE..."
 for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -b "" -s base -h $LOCALHOST -p $PORT '+extensibleObject' > $SEARCHOUT 2>&1
+	$LDAPSEARCH -b "" -s base -h $LOCALHOST -p $PORT1 \
+		'+extensibleObject' > $SEARCHOUT 2>&1
 	RC=$?
 	if test $RC = 0 ; then
 		break
@@ -48,25 +42,43 @@ for i in 0 1 2 3 4 5; do
 	sleep 5
 done
 
-if test $RC = 0 -a $MONITORDB = yes ; then
-	echo "Using ldapsearch to retrieve the cn=Monitor..."
-	$LDAPSEARCH -b "cn=Monitor" -s base -h $LOCALHOST -p $PORT '+extensibleObject' >> $SEARCHOUT 2>&1
+if test $RC = 0 ; then
+	echo "Using ldapsearch to retrieve the cn=Subschema..."
+	$LDAPSEARCH -b "cn=Subschema" -s base -h $LOCALHOST -p $PORT1 \
+		'(&(objectClasses=top)(objectClasses=2.5.6.0))' cn objectClass \
+		>> $SEARCHOUT  2>&1
 	RC=$?
+
 fi
 
-kill -HUP $PID
+count=2
+if test $RC = 0 ; then
+	case $MONITORDB in yes | mod)
+		count=3
+		echo "Using ldapsearch to retrieve the cn=Monitor..."
+		$LDAPSEARCH -b "cn=Monitor" -s base -h $LOCALHOST -p $PORT1 \
+			'+extensibleObject' >> $SEARCHOUT 2>&1
+		RC=$?
+		;;
+	esac
+fi
+
+test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
 cat $SEARCHOUT
+
 
 if test $RC != 0 ; then
 	echo ">>>>> Test failed"
 else
-	if grep "TLS:" $SEARCHOUT; then
-		RC=-1
+	RC=`grep '^dn:' $SEARCHOUT | wc -l`
+	if test $RC != $count ; then
+		echo ">>>>> Test failed: expected $count entries, got" $RC
+		RC=1
 	else
-	    echo ">>>>> Test succeeded"
+		echo ">>>>> Test succeeded"
+		RC=0
 	fi
 fi
-
 
 exit $RC
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test004-modify b/OpenLDAP/OpenLDAP/tests/scripts/test004-modify
--- a/OpenLDAP/OpenLDAP/tests/scripts/test004-modify
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test004-modify
@@ -1,53 +1,46 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test004-modify,v 1.35.2.6 2003/02/24 16:16:54 kurt Exp $
-
-SRCDIR="."
-if test $# -ge 1 ; then
-	SRCDIR=$1; shift
-fi
-BACKEND=bdb
-if test $# -ge 1 ; then
-	BACKEND=$1; shift
-fi
-MONITORDB=no
-if test $# -ge 1 ; then
-	MONITORDB=$1; shift
-fi
-WAIT=0
-if test $# -ge 1 ; then
-	WAIT=1; shift
-fi
+# $OpenLDAP: pkg/ldap/tests/scripts/test004-modify,v 1.53.2.5 2006/01/03 22:16:28 kurt Exp $
+## This work is part of OpenLDAP Software <http://www.openldap.org/>.
+##
+## Copyright 1998-2006 The OpenLDAP Foundation.
+## All rights reserved.
+##
+## Redistribution and use in source and binary forms, with or without
+## modification, are permitted only as authorized by the OpenLDAP
+## Public License.
+##
+## A copy of this license is available in the file LICENSE in the
+## top-level directory of the distribution or, alternatively, at
+## <http://www.OpenLDAP.org/license.html>.
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
-echo "running defines.sh $SRCDIR $BACKEND"
-. $SRCDIR/scripts/defines.sh
-
-echo "Cleaning up in $DBDIR..."
-
-rm -f $DBDIR/[!C]*
+mkdir -p $TESTDIR $DBDIR1
 
 echo "Running slapadd to build slapd database..."
-. $CONFFILTER $BACKEND $MONITORDB < $CONF > $DBCONF
-$SLAPADD -f $DBCONF -l $LDIFORDERED
+. $CONFFILTER $BACKEND $MONITORDB < $CONF > $CONF1
+$SLAPADD -f $CONF1 -l $LDIFORDERED
 RC=$?
 if test $RC != 0 ; then
 	echo "slapadd failed ($RC)!"
 	exit $RC
 fi
 
-echo "Starting slapd on TCP/IP port $PORT..."
-$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
+echo "Starting slapd on TCP/IP port $PORT1..."
+$SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
     echo PID $PID
     read foo
 fi
+KILLPIDS="$PID"
+
+sleep 1
 
 echo "Testing slapd modify operations..."
 for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT \
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
 		'objectclass=*' > /dev/null 2>&1
 	RC=$?
 	if test $RC = 0 ; then
@@ -59,18 +52,18 @@ done
 
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
 echo "Testing modify, add, and delete..."
-$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT -w $PASSWD > \
+$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
 	$TESTOUT 2>&1 << EOMODS
 version: 1
 
 # LEADING COMMENT AND WHITE SPACE
 
-dn: cn=James A Jones 1,ou=Alumni Association,ou=People,o=University of Michigan,c=US
+dn: cn=James A Jones 1,ou=Alumni Association,ou=People,dc=example,dc=com
 # EMBEDDED COMMENT
 changetype: modify
 add: drink
@@ -88,7 +81,7 @@ sn: Jones
 add: sn
 sn: Jones
 
-dn: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
+dn: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
 changetype: modify
 # EMBEDDED COMMENT
  CONTINUED
@@ -99,60 +92,122 @@ replace: drink
 drink: Iced Tea
 drink: Mad Dog 20/20
 
-dn: cn=ITD Staff,ou=Groups,o=University of Michigan,c=US
+dn: cn=ITD Staff,ou=Groups,dc=example,dc=com
 changetype: modify
-delete: member
-member: cn=James A Jones 2,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
-member: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
+delete: uniquemember
+uniquemember: cn=James A Jones 2,ou=Information Technology Division,
+ ou=People,dc=example,dc=com
+uniquemember: cn=Bjorn Jensen,ou=Information Technology Division,
+ ou=People,dc=example,dc=com
 -
-add: member
-member: cn=Dorothy Stevens,ou=Alumni Association,ou=People,o=University of Michigan,c=US
-member: cn=James A Jones 1,ou=Alumni Association,ou=People,o=University of Michigan,c=US
+add: uniquemember
+uniquemember: cn=Dorothy Stevens,ou=Alumni Association,
+ ou=People,dc=example,dc=com
+uniquemember: cn=James A Jones 1,ou=Alumni Association,
+ ou=People,dc=example,dc=com
+-
+add: objectClass
+objectClass: OpenLDAPdisplayableObject
+objectClass: pkiUser
+objectClass: userSecurityInformation
+-
+delete: objectClass
+objectClass: userSecurityInformation
+objectClass: pkiUser
+objectClass: OpenLDAPdisplayableObject
 
-dn: cn=All Staff,ou=Groups,o=University of Michigan,c=US
+dn: cn=All Staff,ou=Groups,dc=example,dc=com
 changetype: modify
 delete: member
 -
 add: member
-member: cn=Dorothy Stevens,ou=Alumni Association,ou=People,o=University of Michigan,c=US
+member: cn=Dorothy Stevens,ou=Alumni Association,ou=People,dc=example,dc=com
 -
 delete: description
+-
+add: objectClass
+objectClass: OpenLDAPdisplayableObject
+objectClass: pkiUser
+objectClass: userSecurityInformation
+-
+delete: objectClass
+objectClass: OpenLDAPdisplayableObject
+objectClass: pkiUser
+objectClass: userSecurityInformation
 
-dn: cn=Gern Jensen,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
+dn: cn=Gern Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
 changetype: add
-objectclass: OpenLDAPperson
+objectclass: testPerson
 cn: Gern Jensen
 sn: Jensen
 uid: gjensen
 title: Chief Investigator, ITD
-postaladdress: ITD $ 535 W. William St $ Ann Arbor, MI 48103
-seealso: cn=All Staff,ou=Groups,o=University of Michigan,c=US
+postaladdress: ITD $ 535 W. William St $ Anytown, MI 48103
+seealso: cn=All Staff,ou=Groups,dc=example,dc=com
 drink: Coffee
-homepostaladdress: 844 Brown St. Apt. 4 $ Ann Arbor, MI 48104
+homepostaladdress: 844 Brown St. Apt. 4 $ Anytown, MI 48104
 description: Very odd
 facsimiletelephonenumber: +1 313 555 7557
 telephonenumber: +1 313 555 8343
 mail: gjensen@mailgw.example.com
 homephone: +1 313 555 8844
+testTime: 20050304001801.234Z
 
-dn: cn=James A Jones 2,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
+dn: cn=James A Jones 2,ou=Information Technology Division,ou=People,dc=example,dc=com
 changetype: delete
 # TRAILING COMMENT AND WHITE SPACE
+
+dn: ou=People,dc=example,dc=com
+changetype: modify
+increment: uidNumber
+uidNumber: 1
+-
+increment: gidNumber
+gidNumber: -1
+
+dn: dc=example,dc=com
+changetype: modify
+# EMPTY SEQUENCE OF CHANGE
 
 EOMODS
 
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapmodify failed ($RC)!"
-	kill -HUP $PID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
+echo "Using ldapmodify to add an empty entry (should fail with protocolError)..."
+$LDAPMODIFY -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
+	 >> $TESTOUT 2>&1 << EOMODS
+dn: cn=Foo Bar,dc=example,dc=com
+changetype: add
+# EMPTY SEQUENCE OF ATTRS
+EOMODS
+
+RC=$?
+case $RC in
+2)
+	echo "	ldapmodify failed ($RC)"
+	;;
+0)
+	echo "	ldapmodify should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit -1
+	;;
+*)
+	echo "	ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+	;;
+esac
+
 echo "Using ldapsearch to retrieve all the entries..."
-$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	    'objectClass=*' > $SEARCHOUT 2>&1
 RC=$?
-kill -HUP $PID
+test $KILLSERVERS != no && kill -HUP $KILLPIDS
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
 	exit $RC
@@ -173,5 +228,4 @@ if test $? != 0 ; then
 fi
 
 echo ">>>>> Test succeeded"
-
 exit 0
diff --git a/OpenLDAP/OpenLDAP/tests/scripts/test007-replication b/OpenLDAP/OpenLDAP/tests/scripts/test007-replication
--- a/OpenLDAP/OpenLDAP/tests/scripts/test007-replication
+++ b/OpenLDAP/OpenLDAP/tests/scripts/test007-replication
@@ -1,68 +1,65 @@
 #! /bin/sh
-# $OpenLDAP: pkg/ldap/tests/scripts/test007-replication,v 1.35.2.10 2003/04/04 20:41:37 kurt Exp $
-
-SRCDIR="."
-if test $# -ge 1 ; then
-	SRCDIR=$1; shift
-fi
-BACKEND=bdb
-if test $# -ge 1 ; then
-	BACKEND=$1; shift
-fi
-MONITORDB=no
-if test $# -ge 1 ; then
-	MONITORDB=$1; shift
-fi
-WAIT=0
-if test $# -ge 1 ; then
-	WAIT=1; shift
-fi
+# $OpenLDAP: pkg/ldap/tests/scripts/test007-replication,v 1.58.2.4 2006/01/03 22:16:28 kurt Exp $
+## This work is part of OpenLDAP Software <http://www.openldap.org/>.
+##
+## Copyright 1998-2006 The OpenLDAP Foundation.
+## All rights reserved.
+##
+## Redistribution and use in source and binary forms, with or without
+## modification, are permitted only as authorized by the OpenLDAP
+## Public License.
+##
+## A copy of this license is available in the file LICENSE in the
+## top-level directory of the distribution or, alternatively, at
+## <http://www.OpenLDAP.org/license.html>.
 
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
-#
-# Test replication:
-# - start master
-# - start slave
-# - start slurpd
-# - populate over ldap
-# - perform some modifies and deleted
-# - retrieve database over ldap and compare against expected results
-#
-
 if test ! -x $SLURPD ; then
-	echo ">>>>> $SLURPD is not executable or do not exist."
+	echo ">>>>> $SLURPD is not executable or does not exist."
 	echo ">>>>> Test skipped."
 	exit 0
 fi
 
-echo "Cleaning up in $DBDIR..."
-rm -f $DBDIR/[!C]*
-echo "Cleaning up in $REPLDIR..."
-rm -rf $REPLDIR/[!C]*
+mkdir -p $TESTDIR $DBDIR1A $DBDIR1B $DBDIR2
 
-echo "Starting master slapd on TCP/IP port $PORT..."
-. $CONFFILTER $BACKEND $MONITORDB < $MASTERCONF > $DBCONF
-$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
+#
+# Test replication:
+# - start master (slapd1)
+# - start slave (slapd2)
+# - start slurpd
+# - populate over ldap
+# - perform some modifies and deleted
+# - attempt to modify the slave (referral or chain)
+# - retrieve database over ldap and compare against expected results
+#
+
+echo "Starting master slapd on TCP/IP port $PORT1..."
+. $CONFFILTER $BACKEND $MONITORDB < $MASTERCONF > $CONF1
+$SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
     echo PID $PID
     read foo
 fi
+KILLPIDS="$PID"
 
-echo "Starting slave slapd on TCP/IP port $SLAVEPORT..."
-. $CONFFILTER $BACKEND $MONITORDB < $SLAVECONF > $REPLCONF
-$SLAPD -f $REPLCONF -h $SLAVEURI -d $LVL $TIMING > $SLAVELOG 2>&1 &
+echo "Starting slave slapd on TCP/IP port $PORT2..."
+. $CONFFILTER $BACKEND $MONITORDB < $SLAVECONF > $CONF2
+$SLAPD -f $CONF2 -h $URI2 -d $LVL $TIMING > $LOG2 2>&1 &
 SLAVEPID=$!
 if test $WAIT != 0 ; then
     echo SLAVEPID $SLAVEPID
     read foo
 fi
+KILLPIDS="$KILLPIDS $SLAVEPID"
+
+sleep 1
 
 echo "Using ldapsearch to check that master slapd is running..."
 for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT \
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT1 \
 		'objectclass=*' > /dev/null 2>&1
 	RC=$?
 	if test $RC = 0 ; then
@@ -74,7 +71,7 @@ done
 
 echo "Using ldapsearch to check that slave slapd is running..."
 for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT \
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT2 \
 		'objectclass=*' > /dev/null 2>&1
 	RC=$?
 	if test $RC = 0 ; then
@@ -85,17 +82,21 @@ for i in 0 1 2 3 4 5; do
 done
 
 echo "Starting slurpd..."
-$SLURPD -f $MASTERCONF -d ${SLURPD_DEBUG-5} -t $REPLDIR > $SLURPLOG 2>&1 &
+$SLURPD -f $CONF1 -d ${SLURPD_DEBUG-5} -t $DBDIR1B > $SLURPLOG 2>&1 &
 SLURPPID=$!
+if test $WAIT != 0 ; then
+    echo SLURPPID $SLURPPID
+    read foo
+fi
+KILLPIDS="$KILLPIDS $SLURPPID"
 
 echo "Using ldapadd to populate the master directory..."
-$LDAPADD -D "$MANAGERDN" -h $LOCALHOST -p $PORT -w $PASSWD < \
+$LDAPADD -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD < \
 	$LDIFORDERED > /dev/null 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapadd failed ($RC)!"
-	kill -HUP $PID $SLAVEPID
-	kill -KILL $SLURPPID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
@@ -108,9 +109,9 @@ echo "Using ldapmodify to modify master directory..."
 # Do some modifications
 #
 
-$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT -w $PASSWD > \
+$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
 	$TESTOUT 2>&1 << EOMODS
-dn: cn=James A Jones 1, ou=Alumni Association, ou=People, o=University of Michigan, c=US
+dn: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com
 changetype: modify
 add: drink
 drink: Orange Juice
@@ -121,27 +122,28 @@ sn: Jones
 add: sn
 sn: Jones
 
-dn: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, dc=example, dc=com
 changetype: modify
 replace: drink
 drink: Iced Tea
 drink: Mad Dog 20/20
 
-dn: cn=ITD Staff,ou=Groups,o=University of Michigan,c=US
+dn: cn=ITD Staff,ou=Groups,dc=example, dc=com
 changetype: modify
-delete: member
-member: cn=James A Jones 2, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
-member: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+delete: uniqueMember
+uniqueMember: cn=James A Jones 2, ou=Information Technology Division,
+ ou=People, dc=example, dc=com
+uniqueMember: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, dc=example, dc=com
 -
-add: member
-member: cn=Dorothy Stevens, ou=Alumni Association, ou=People, o=University of Michigan, c=US
-member: cn=James A Jones 1, ou=Alumni Association, ou=People, o=University of Michigan, c=US
+add: uniqueMember
+uniqueMember: cn=Dorothy Stevens, ou=Alumni Association, ou=People, dc=example, dc=com
+uniqueMember: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com
 
-dn: cn=All Staff,ou=Groups,o=University of Michigan,c=US
+dn: cn=All Staff,ou=Groups,dc=example, dc=com
 changetype: modify
 delete: description
 
-dn: cn=Gern Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Gern Jensen, ou=Information Technology Division, ou=People, dc=example, dc=com
 changetype: add
 objectclass: OpenLDAPperson
 cn: Gern Jensen
@@ -149,7 +151,7 @@ sn: Jensen
 uid: gjensen
 title: Chief Investigator, ITD
 postaladdress: ITD $ 535 W. William St $ Ann Arbor, MI 48103
-seealso: cn=All Staff, ou=Groups, o=University of Michigan, c=US
+seealso: cn=All Staff, ou=Groups, dc=example, dc=com
 drink: Coffee
 homepostaladdress: 844 Brown St. Apt. 4 $ Ann Arbor, MI 48104
 description: Very odd
@@ -158,69 +160,181 @@ telephonenumber: +1 313 555 8343
 mail: gjensen@mailgw.example.com
 homephone: +1 313 555 8844
 
-dn: ou=Retired, ou=People, o=University of Michigan, c=US
+dn: ou=Retired, ou=People, dc=example, dc=com
 changetype: add
 objectclass: organizationalUnit
 ou: Retired
 
-dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, dc=example, dc=com
 changetype: add
 objectclass: OpenLDAPperson
 cn: Rosco P. Coltrane
 sn: Coltrane
 uid: rosco
 
-dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Rosco P. Coltrane, ou=Information Technology Division, ou=People, dc=example, dc=com
 changetype: modrdn
 newrdn: cn=Rosco P. Coltrane
 deleteoldrdn: 1
-newsuperior: ou=Retired, ou=People, o=University of Michigan, c=US
+newsuperior: ou=Retired, ou=People, dc=example, dc=com
 
-dn: cn=James A Jones 2, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=James A Jones 2, ou=Information Technology Division, ou=People, dc=example, dc=com
 changetype: delete
 
 EOMODS
 
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 echo "Waiting 15 seconds for slurpd to send changes..."
 sleep 15
 
+echo "Stopping the slave..."
+kill -HUP $SLAVEPID
+KILLPIDS="$PID $SLURPPID"
+
+echo "Waiting 5 seconds for slave slapd to die..."
+sleep 5
+
+echo "Applying more changes to the master slapd..."
+$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com
+changetype: modify
+add: description
+description: This change was applied after killing the slave slapd...
+
+EOMODS
+
+RC=$?
+
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+
+echo "Stopping slurpd..."
+kill -HUP $SLURPPID
+KILLPIDS="$PID"
+
+echo "Waiting 5 seconds for slurpd to die..."
+sleep 5
+
+echo "Applying more changes to the master slapd..."
+$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
+	$TESTOUT 2>&1 << EOMODS
+dn: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com
+changetype: modify
+add: description
+description: This change was applied after killing slurpd...
+
+EOMODS
+
+RC=$?
+
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Restarting slave slapd on TCP/IP port $PORT2..."
+echo "RESTART" >> $LOG2
+$SLAPD -f $CONF2 -h $URI2 -d $LVL $TIMING >> $LOG2 2>&1 &
+SLAVEPID=$!
+if test $WAIT != 0 ; then
+    echo SLAVEPID $SLAVEPID
+    read foo
+fi
+KILLPIDS="$KILLPIDS $SLAVEPID"
+
+sleep 1
+
+echo "Using ldapsearch to check that slave slapd is running..."
+for i in 0 1 2 3 4 5; do
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT2 \
+		'objectclass=*' > /dev/null 2>&1
+	RC=$?
+	if test $RC = 0 ; then
+		break
+	fi
+	echo "Waiting 5 seconds for slapd to start..."
+	sleep 5
+done
+
+echo "Restarting slurpd..."
+echo "RESTART" >> $SLURPLOG
+$SLURPD -f $CONF1 -d ${SLURPD_DEBUG-5} -t $DBDIR1B >> $SLURPLOG 2>&1 &
+SLURPPID=$!
+if test $WAIT != 0 ; then
+    echo SLURPPID $SLURPPID
+    read foo
+fi
+KILLPIDS="$KILLPIDS $SLURPPID"
+
+echo "Waiting 15 seconds for slurpd to send changes..."
+sleep 15
+
+if test ! $BACKLDAP = "ldapno" ; then
+	echo "Try updating the slave slapd..."
+	$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT2 -w $PASSWD > \
+		$TESTOUT 2>&1 << EOMODS
+dn: cn=James A Jones 1, ou=Alumni Association, ou=People, dc=example, dc=com
+changetype: modify
+add: description
+description: This write must fail because directed to a shadow context,
+description: unless the chain overlay is configured appropriately ;)
+
+EOMODS
+
+	RC=$?
+	if test $RC != 0 ; then
+		echo "ldapmodify failed ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit $RC
+	fi
+
+	echo "Waiting 15 seconds for slurpd to send changes..."
+	sleep 15
+fi
+
 echo "Using ldapsearch to read all the entries from the master..."
-$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	'objectclass=*' > $MASTEROUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	kill -HUP $PID $SLAVEPID
-	kill -KILL $SLURPPID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
 echo "Using ldapsearch to read all the entries from the slave..."
-$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $SLAVEPORT \
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT2 \
 	'objectclass=*' > $SLAVEOUT 2>&1
 RC=$?
 
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
-	kill -HUP $PID $SLAVEPID
-	kill -KILL $SLURPPID
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
 
-kill -HUP $PID $SLAVEPID
-kill -KILL $SLURPPID
+test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
-SEARCHOUT=$MASTEROUT
-LDIF=$SLAVEOUT
-
-echo "Filtering ldapsearch results..."
-. $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
-echo "Filtering original ldif used to create database..."
-. $LDIFFILTER < $LDIF > $LDIFFLT
+echo "Filtering master results..."
+. $LDIFFILTER < $MASTEROUT > $MASTERFLT
+echo "Filtering slave results..."
+. $LDIFFILTER < $SLAVEOUT > $SLAVEFLT
 
 echo "Comparing retrieved entries from master and slave..."
-$CMP $SEARCHFLT $LDIFFLT > $CMPOUT
+$CMP $MASTERFLT $SLAVEFLT > $CMPOUT
 
 if test $? != 0 ; then
 	echo "test failed - master and slave databases differ"
@@ -228,6 +342,4 @@ if test $? != 0 ; then
 fi
 
 echo ">>>>> Test succeeded"
-
-
 exit 0
diff --git a/cvs/cvs/zlib/Makefile.in b/cvs/cvs/zlib/Makefile.in
--- a/cvs/cvs/zlib/Makefile.in
+++ b/cvs/cvs/zlib/Makefile.in
@@ -1,14 +1,19 @@
 # Makefile for zlib
-# Copyright (C) 1995-1996 Jean-loup Gailly.
-# For conditions of distribution and use, see copyright notice in zlib.h 
+# Copyright (C) 1995-2005 Jean-loup Gailly.
+# For conditions of distribution and use, see copyright notice in zlib.h
 
 srcdir     = @srcdir@
 top_srcdir = @top_srcdir@
 VPATH      = @srcdir@
 
 # To compile and test, type:
-#   ./configure; make test
+#    ./configure; make test
 # The call of configure is optional if you don't have special requirements
+# If you wish to build zlib as a shared library, use: ./configure -s
+
+# To use the asm code, type:
+#    cp contrib/asm?86/match.S ./match.S
+#    make LOC=-DASMV OBJA=match.o
 
 # To install /usr/local/lib/libz.* and /usr/local/include/zlib.h, type:
 #    make install
@@ -23,107 +28,231 @@ CFLAGS=@CFLAGS@
 #CFLAGS=-O3 -Wall -Wwrite-strings -Wpointer-arith -Wconversion \
 #           -Wstrict-prototypes -Wmissing-prototypes
 
-LDFLAGS=@LDFLAGS@
+LDFLAGS=libz.a @LDFLAGS@
 LDSHARED=$(CC)
+CPP=$(CC) -E
 
-VER=1.0.4
 LIBS=libz.a
+SHAREDLIB=libz.so
+SHAREDLIBV=libz.so.1.2.3
+SHAREDLIBM=libz.so.1
 
 # For CVS, separate AR and ARFLAGS.
 AR=ar
-RANLIB=ranlib
-TAR=tar
+RANLIB=@RANLIB@
+AMTAR=@AMTAR@
+SHELL=/bin/sh
+EXE=
 
 prefix=@prefix@
-exec_prefix = @exec_prefix@
+exec_prefix = $(prefix)
+libdir = ${exec_prefix}/lib
+includedir = ${prefix}/include
+mandir = ${prefix}/share/man
+man3dir = ${mandir}/man3
 
 OBJS = adler32.o compress.o crc32.o gzio.o uncompr.o deflate.o trees.o \
-       zutil.o inflate.o infblock.o inftrees.o infcodes.o infutil.o inffast.o
+       zutil.o inflate.o infback.o inftrees.o inffast.o
+
+OBJA =
+# to use the asm code: make OBJA=match.o
 
 TEST_OBJS = example.o minigzip.o
 
-# build_zlib.com added for CVS
-DISTFILES = README INDEX ChangeLog configure Makefile.*[a-z0-9] Make_vms.com \
-	    descrip.mms zlib.def zlib.rc algorithm.doc *.[ch] \
-	    build_zlib.com
+DISTFILES = README FAQ INDEX ChangeLog configure Makefile.* *.[ch] \
+  make_vms.com algorithm.txt zlib.3 \
+  amiga/[a-z0-9ABD-Z]* \
+  as400/[a-z0-9ABD-Z]* \
+  msdos/[a-z0-9ABD-Z]* \
+  qnx/package.qpg \
+  win32/[a-z0-9ABD-Z]* \
+  contrib/RE*.contrib \
+  contrib/ada/[a-z0-9]* \
+  contrib/asm586/match.S contrib/asm586/README.586 \
+  contrib/asm686/match.S contrib/asm686/README.686 \
+  contrib/blast/[a-z0-9ABD-Z]* \
+  contrib/delphi/[a-z0-9ABD-Z]* \
+  contrib/infback9/[a-z0-9ABD-Z]* \
+  contrib/inflate86/[a-z0-9ABD-Z]* \
+  contrib/iostream/[a-z0-9ABD-Z]* \
+  contrib/iostream2/[a-z0-9ABD-Z]* \
+  contrib/iostream3/[a-z0-9ABD-Z]* \
+  contrib/masm686/[a-z0-9ABD-Z]* \
+  contrib/masmx64/[a-z0-9ABD-Z]* \
+  contrib/masmx86/[a-z0-9ABD-Z]* \
+  contrib/minizip/[a-z0-9ABD-Z]* contrib/minizip/Ch* \
+  contrib/pascal/[a-z0-9ABD-Z]* \
+  contrib/puff/[a-z0-9ABD-Z]* \
+  contrib/testzlib/[a-z0-9ABD-Z]* \
+  contrib/untgz/[a-z0-9ABD-Z]* \
+  contrib/vstudio/readme.txt \
+  contrib/vstudio/vc7/[a-z0-9ABD-Z]* \
+  contrib/vstudio/vc8/[a-z0-9ABD-Z]* \
+  old/[a-np-z0-9ABD-Z]* old/os2/[a-z0-9ABD-Z]* \
+  examples/[a-z0-9ABD-Z]* \
+  libz.dep libz.dsp libz.mak .cvsignore
+
+# for CVS's distdir & Makefile targets
+subdir = zlib
 
 # For CVS, just build libz.a
 all: libz.a
 
-test: all
-	./example
-	echo hello world | ./minigzip | ./minigzip -d 
+# To reenable make test
+all-original: example$(EXE) minigzip$(EXE)
+
+check test: all-original
+	@LD_LIBRARY_PATH=.:$(LD_LIBRARY_PATH) ; export LD_LIBRARY_PATH; \
+	echo hello world | ./minigzip | ./minigzip -d || \
+	  echo '		*** minigzip test FAILED ***' ; \
+	if ./example; then \
+	  echo '		*** zlib test OK ***'; \
+	else \
+	  echo '		*** zlib test FAILED ***'; \
+	fi
 
 # For CVS, use an explict rc after $(AR).
-libz.a: $(OBJS)
-	$(AR) rc $@ $(OBJS)
-	-@ ($(RANLIB) $@ || true) 2>/dev/null
+libz.a: $(OBJS) $(OBJA)
+	$(AR) rc $@ $(OBJS) $(OBJA)
+	-@ ($(RANLIB) $@ || true) >/dev/null 2>&1
 
-libz.so.$(VER): $(OBJS)
+match.o: match.S
+	$(CPP) match.S > _match.s
+	$(CC) -c _match.s
+	mv _match.o match.o
+	rm -f _match.s
+
+$(SHAREDLIBV): $(OBJS)
 	$(LDSHARED) -o $@ $(OBJS)
-	rm -f libz.so; ln -s $@ libz.so
+	rm -f $(SHAREDLIB) $(SHAREDLIBM)
+	ln -s $@ $(SHAREDLIB)
+	ln -s $@ $(SHAREDLIBM)
 
-example: example.o $(LIBS)
-	$(CC) $(CFLAGS) -o $@ example.o $(LDFLAGS) $(LIBS)
+example$(EXE): example.o $(LIBS)
+	$(CC) $(CFLAGS) -o $@ example.o $(LDFLAGS)
 
-minigzip: minigzip.o $(LIBS)
-	$(CC) $(CFLAGS) -o $@ minigzip.o $(LDFLAGS) $(LIBS)
+minigzip$(EXE): minigzip.o $(LIBS)
+	$(CC) $(CFLAGS) -o $@ minigzip.o $(LDFLAGS)
 
-# For CVS, remove the install and uninstall targets.
-install:
+# For CVS, make install dependant on all and remove the uninstall target.
+install: all
 uninstall:
 .PHONY: install uninstall
+
+# Remove targets for CVS
+dvi info pdf ps:
+.PHONY: dvi info pdf ps
+installcheck:
+.PHONY: installcheck
+
+#install: $(LIBS)
+#	-@if [ ! -d $(exec_prefix) ]; then mkdir -p $(exec_prefix); fi
+#	-@if [ ! -d $(includedir)  ]; then mkdir -p $(includedir); fi
+#	-@if [ ! -d $(libdir)      ]; then mkdir -p $(libdir); fi
+#	-@if [ ! -d $(man3dir)     ]; then mkdir -p $(man3dir); fi
+#	cp zlib.h zconf.h $(includedir)
+#	chmod 644 $(includedir)/zlib.h $(includedir)/zconf.h
+#	cp $(LIBS) $(libdir)
+#	cd $(libdir); chmod 755 $(LIBS)
+#	-@(cd $(libdir); $(RANLIB) libz.a || true) >/dev/null 2>&1
+#	cd $(libdir); if test -f $(SHAREDLIBV); then \
+#	  rm -f $(SHAREDLIB) $(SHAREDLIBM); \
+#	  ln -s $(SHAREDLIBV) $(SHAREDLIB); \
+#	  ln -s $(SHAREDLIBV) $(SHAREDLIBM); \
+#	  (ldconfig || true)  >/dev/null 2>&1; \
+#	fi
+#	cp zlib.3 $(man3dir)
+#	chmod 644 $(man3dir)/zlib.3
+# The ranlib in install is needed on NeXTSTEP which checks file times
+# ldconfig is for Linux
+
+#uninstall:
+#	cd $(includedir); \
+#	cd $(libdir); rm -f libz.a; \
+#	if test -f $(SHAREDLIBV); then \
+#	  rm -f $(SHAREDLIBV) $(SHAREDLIB) $(SHAREDLIBM); \
+#	fi
+#	cd $(man3dir); rm -f zlib.3
 
 installdirs:
 .PHONY: installdirs
 
-# mostlyclean added for CVS.
-clean mostlyclean:
-	rm -f *.o *~ example minigzip libz.a libz.so* foo.gz
-
-# distclean and realclean added for CVS.
-distclean realclean: clean
-	rm -f Makefile
-.PHONY: distclean realclean
-
-# dist-dir added for CVS.
-dist-dir:
-	mkdir ${DISTDIR}
-	for i in `cd $(srcdir); echo ${DISTFILES}`; do \
-	  ln $(srcdir)/$${i} ${DISTDIR}; \
+# distdir added for CVS.
+top_builddir = ..
+PACKAGE = @PACKAGE@
+VERSION = @VERSION@
+distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)
+distdir:
+	@d=$(srcdir); \
+	for file in `cd $$d; echo $(DISTFILES)`; do \
+	  if test -d $(distdir)/`dirname $$file`; then \
+	    :; \
+	  else \
+	    mkdir $(distdir)/`dirname $$file`; \
+	  fi; \
+	  if test -d $$d/$$file; then \
+	    cp -pR $$d/$$file $(distdir) \
+	    || exit 1; \
+	  else \
+	    test -f $(distdir)/$$file \
+	    || cp -p $$d/$$file $(distdir)/$$file \
+	    || exit 1; \
+	  fi; \
 	done
-.PHONY: dist-dir
+.PHONY: distdir
 
-# ls added for CVS.
-ls:
-	@echo $(DISTFILES)
-.PHONY: ls
+mostlyclean: clean
+clean:
+	rm -f *.o *~ example$(EXE) minigzip$(EXE) \
+	   libz.a libz.so* foo.gz so_locations \
+	   _match.s maketree contrib/infback9/*.o \
+	   tags
+.PHONY: mostlyclean clean
+
+realclean: distclean
+maintainer-clean: distclean
+distclean: clean
+	rm -f Makefile .DS_Store
 
 zip:
 	mv Makefile Makefile~; cp -p Makefile.in Makefile
+	rm -f test.c ztest*.c contrib/minizip/test.zip
 	v=`sed -n -e 's/\.//g' -e '/VERSION "/s/.*"\(.*\)".*/\1/p' < zlib.h`;\
 	zip -ul9 zlib$$v $(DISTFILES)
 	mv Makefile~ Makefile
 
 dist:
 	mv Makefile Makefile~; cp -p Makefile.in Makefile
+	rm -f test.c ztest*.c contrib/minizip/test.zip
 	d=zlib-`sed -n '/VERSION "/s/.*"\(.*\)".*/\1/p' < zlib.h`;\
 	rm -f $$d.tar.gz; \
 	if test ! -d ../$$d; then rm -f ../$$d; ln -s `pwd` ../$$d; fi; \
 	files=""; \
 	for f in $(DISTFILES); do files="$$files $$d/$$f"; done; \
 	cd ..; \
-	GZIP=-9 $(TAR) chofz $$d/$$d.tar.gz $$files; \
+	GZIP=-9 $(AMTAR) chofz $$d/$$d.tar.gz $$files; \
 	if test ! -d $$d; then rm -f $$d; fi
 	mv Makefile~ Makefile
 
-tags:	
-	etags *.[ch]
+.PHONY: tags
+tags: TAGS
+
+TAGS:
+	tags=; \
+	here=`pwd`; \
+	list=`(echo *.[ch] && cd $(srcdir) && echo *.[ch]) |sort |uniq`; \
+	unique=`for i in $$list; do \
+	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
+	  done | \
+	  $(AWK) '    { files[$$0] = 1; } \
+	       END { for (i in files) print i; }'`; \
+	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
+	  || etags $(ETAGS_ARGS) $$tags $$unique $(LISP)
 
 # Makefile target added for CVS.
-subdir = zlib
-Makefile: ../config.status Makefile.in
-	cd .. && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= ./config.status
+Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
+	cd $(top_builddir) \
+	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
 
 depend:
 	makedepend -- $(CFLAGS) -- *.[ch]
@@ -132,19 +261,15 @@ depend:
 
 adler32.o: zlib.h zconf.h
 compress.o: zlib.h zconf.h
-crc32.o: zlib.h zconf.h
+crc32.o: crc32.h zlib.h zconf.h
 deflate.o: deflate.h zutil.h zlib.h zconf.h
 example.o: zlib.h zconf.h
 gzio.o: zutil.h zlib.h zconf.h
-infblock.o: infblock.h inftrees.h infcodes.h infutil.h zutil.h zlib.h zconf.h
-infcodes.o: zutil.h zlib.h zconf.h
-infcodes.o: inftrees.h infblock.h infcodes.h infutil.h inffast.h
-inffast.o: zutil.h zlib.h zconf.h inftrees.h
-inffast.o: infblock.h infcodes.h infutil.h inffast.h
-inflate.o: zutil.h zlib.h zconf.h infblock.h
+inffast.o: zutil.h zlib.h zconf.h inftrees.h inflate.h inffast.h
+inflate.o: zutil.h zlib.h zconf.h inftrees.h inflate.h inffast.h
+infback.o: zutil.h zlib.h zconf.h inftrees.h inflate.h inffast.h
 inftrees.o: zutil.h zlib.h zconf.h inftrees.h
-infutil.o: zutil.h zlib.h zconf.h infblock.h inftrees.h infcodes.h infutil.h
-minigzip.o:  zlib.h zconf.h 
-trees.o: deflate.h zutil.h zlib.h zconf.h 
+minigzip.o: zlib.h zconf.h
+trees.o: deflate.h zutil.h zlib.h zconf.h trees.h
 uncompr.o: zlib.h zconf.h
-zutil.o: zutil.h zlib.h zconf.h  
+zutil.o: zutil.h zlib.h zconf.h
diff --git a/efax/efax/fax b/efax/efax/fax
--- a/efax/efax/fax
+++ b/efax/efax/fax
@@ -27,8 +27,26 @@ EFIX=efix
 # name or the UUCP locking mechanism will fail.  For example, if
 # /dev/modem is a link to /dev/cua1, then getty, uucp, kermit,
 # pppd, dip, etc. must *all* use either /dev/modem or /dev/cua1.
+#
+# To support port sharing the answer mode device may be different
+# than the send or receive device.
+#
+# The alternate devices are used when a primary device doesn't exist.
+# This can be useful when supporting multiple kinds of modems.
 
-DEV=cua1
+DEV=cu.usbmodem
+DEVANSWER=tty.usbmodem
+
+ALTDEV=cu.modem
+ALTDEVANSWER=tty.modem
+
+if [ ! -e /dev/$DEV -a "x$ALTDEV" != "x" -a -e /dev/$ALTDEV ]; then
+    DEV=$ALTDEV
+fi
+
+if [ ! -e /dev/$DEVANSWER -a "x$ALTDEVANSWER" != "x" -a -e /dev/$ALTDEVANSWER ]; then
+    DEVANSWER=$ALTDEVANSWER
+fi
 
 # Your fax number in international format, 20 characters maximum.
 # Use only digits, spaces, and the "+" character.
@@ -81,12 +99,12 @@ DIALSUFFIX=""
 # conventions. Protect with single quotes for delayed evaluation.
 # Add a leading '#' to the file name to use binary format.
 
-LOCK='-x /var/lock/LCK..$DEV' 			# modern systems
+# LOCK='-x /var/lock/LCK..$DEV'			# modern systems
 # LOCK='-x /usr/spool/uucp/LCK..$DEV'		# older systems
 # LOCK='-x /var/lock/LCK..$DEV -x /var/spool/uucp/LCK..$DEV' # both
 # LOCK='-x #/usr/spool/uucp/LCK..$DEV'		# binary format
 # LOCK='-x /usr/spool/locks/LK.047.040.011'	# SysV style names
-# LOCK=''					# no lock file
+LOCK=''					# no lock file
 
 # Uncomment one of the following lines to force xon/xoff flow
 # control only if you have one of the types of modems listed.
@@ -202,11 +220,11 @@ PRINT='$EFIX -ve -p$PAGEDIM -r300 -s0.98 -d0,0.125 -o$PRTYPE $f'
 # VIEW='$EFIX -ve -p$PAGEDIM -r200 -opgm $f' 	# 50dpi: fast, whole-page view
 VIEW='$EFIX -ve -p$PAGEDIM -r300 -opgm $f'	# 75dpi: slower, readable size
 
-# Commands to set up modem.  "-iZ -iE0&D2S7=120 -i&C0"
+# Commands to set up modem.  "-iZ -iE0&D2S7=120"
 # works with almost all modems.  See the efax(1) man page for
 # details.
 
-INIT="-iZ -i&FE0&D2S7=120 -i&C0"
+INIT="-iZ -i&FE0&D2S7=120"
 
 # Command(s) to reset modem when efax finishes. "-kZ" works in
 # almost all cases.
@@ -430,24 +448,6 @@ ERR=0
 
 $NICE true 2>/dev/null ; case $? in 0) ;; *) NICE="" ;; esac
 
-# -------- resolve dependencies on command-line arguments
-
-eval LOCK=\"$LOCK\"			# depends on DEV
-
-# make device name w/o directories
-
-case $DEV in
-	*/*) DEVN=`echo $DEV|sed -e s./._.g` ;;
-	*) DEVN=$DEV ;;
-esac
-
-case $PAGE in
-	letter)	PAGEDIM="$PAGE_letter" ;;
-	legal) 	PAGEDIM="$PAGE_legal" ;;
-	a4) 	PAGEDIM="$PAGE_a4" ;;
-	*) 	echo "Error: PAGE=\"${PAGE}\" not valid." ; exit 2 ;;
-esac	
-
 # --- check for a command or alias and optional flags
 
 cmd=""
@@ -467,6 +467,33 @@ case $0 in
 	done
 ;; 
 esac
+
+
+# -------- If answer mode use the optional answer device
+
+if [ "x$cmd" = "xanswer" ]; then
+	if [ "x$DEVANSWER" != "x" ]; then
+		DEV=$DEVANSWER
+	fi
+fi
+
+# -------- resolve dependencies on command-line arguments
+
+eval LOCK=\"$LOCK\"			# depends on DEV
+
+# make device name w/o directories
+
+case $DEV in
+	*/*) DEVN=`echo $DEV|sed -e s./._.g` ;;
+	*) DEVN=$DEV ;;
+esac
+
+case $PAGE in
+	letter)	PAGEDIM="$PAGE_letter" ;;
+	legal) 	PAGEDIM="$PAGE_legal" ;;
+	a4) 	PAGEDIM="$PAGE_a4" ;;
+	*) 	echo "Error: PAGE=\"${PAGE}\" not valid." ; exit 2 ;;
+esac	
 
 # -------- functions
 
@@ -503,7 +530,7 @@ while : ; do 	# so we can use `break' to get to the end of the script
 
 case $cmd in 
 
-# fax answer : clean up logs and exec efax. normally run by init(8).
+# fax answer : clean up logs and exec efax. normally run by launchd(8).
 
 	answer)
 
@@ -520,23 +547,24 @@ case $cmd in
 
 	for f in ${DEVN}.[0-9]*  	# clean up old log files
 	do
-	  egrep	"done, returning $NOLOG|exec'ing" $f >/dev/null 2>/dev/null
-	  case $? in
-	  0) 
-	  	$RM $f
-	  ;;
-	  1)    FILES=`sed -n -e  '/received ->/s/^.*-> \(.*\)$/\1/p' $f`
-		FILES=`echo $FILES`
-		REMID=`sed -n -e '/remote ID ->/s/^.*-> \(.*\)$/\1/p' \
-			-e tok -e b -e ':ok' -e q $f`
-		case $REMID in '') REMID='?' ;; esac
-		eval $NOTIFY
-		echo   >>${LOGDIR}/${DEVN}.log && \
-		cat $f >>${LOGDIR}/${DEVN}.log && \
-  		$RM $f || \
-		echo "Error: $FAX cannot save log files" >>$CONSOLE
-	  ;;
-	  esac
+	  if [ -r $f ]
+	  then
+	    egrep	"done, returning $NOLOG|exec'ing" $f >/dev/null 2>/dev/null
+	    case $? in
+	    1)    FILES=`sed -n -e  '/received ->/s/^.*-> \(.*\)$/\1/p' $f`
+		  FILES=`echo $FILES`
+		  REMID=`sed -n -e '/remote ID ->/s/^.*-> \(.*\)$/\1/p' \
+			  -e tok -e b -e ':ok' -e q $f`
+		  case $REMID in '') REMID='?' ;; esac
+		  eval $NOTIFY
+	    ;;
+	    esac
+
+	    echo   >>${LOGDIR}/${DEVN}.log && \
+	    cat $f >>${LOGDIR}/${DEVN}.log && \
+  	    $RM $f || \
+	    echo "Error: $FAX cannot save log files" >>$CONSOLE
+	  fi
 	done	
 
 	while [ -f ${DEVN}.stop ] ; do sleep 15 ; done
diff --git a/gcc/contrib/gcc_update b/gcc/contrib/gcc_update
--- a/gcc/contrib/gcc_update
+++ b/gcc/contrib/gcc_update
@@ -1,10 +1,19 @@
 #! /bin/sh
+# APPLE LOCAL file mainline
 #
-# Update a local CVS tree from the GCC repository, with an emphasis
+# Update a local Subversion tree from the GCC repository, with an emphasis
 # on treating generated files correctly, so that autoconf, gperf et
 # al are not required for the ``end'' user.
 #
-# By default all command-line options are passed to `cvs update` in
+# (C) 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005 Free Software Foundation
+# Originally by Gerald Pfeifer <pfeifer@dbai.tuwien.ac.at>, August 1998.
+#
+# This script is Free Software, and it can be copied, distributed and
+# modified as defined in the GNU General Public License.  A copy of
+# its license can be downloaded from http://www.gnu.org/copyleft/gpl.html
+#
+#
+# By default all command-line options are passed to `svn update` in
 # addition to $UPDATE_OPTIONS (defined below). If the first parameter
 # reads --nostdflags, $UPDATE_OPTIONS as well as this parameter itself
 # are omitted.
@@ -12,103 +21,101 @@
 # If the first parameter reads --patch, the second parameter is considered
 # a patch file.
 #
-# If the first parameter is --touch, no cvs operation will be performed,
+# If the first parameter is --touch, no svn operation will be performed,
 # only generated files that appear to be out of date in the local tree
 # will be touched.
 #
 # If the first parameter is --list, a list of the generated files and
 # their dependencies will be printed; --help prints this message.
 #
+# If the first parameter is --silent, this script prints nothing other
+# than error messages; the second parameter is then interpreted as above.
+#
 # Examples:
 #
-# contrib/gcc_update -r gcc_latest_snapshot
-# contrib/gcc_update -A
-# contrib/gcc_update --nostdflags -P -r gcc-2_95-branch gcc/testsuite
+# contrib/gcc_update -r 8712
 # contrib/gcc_update --patch some-patch
 # contrib/gcc_update --touch
 # contrib/gcc_update --list
-#
-#
-# (C) 1998, 1999, 2000, 2001, 2002, 2003 Free Software Foundation
-# Originally by Gerald Pfeifer <pfeifer@dbai.tuwien.ac.at>, August 1998.
-#
-# This script is Free Software, and it can be copied, distributed and
-# modified as defined in the GNU General Public License.  A copy of
-# its license can be downloaded from http://www.gnu.org/copyleft/gpl.html
 
 
-# Default options used when updating via CVS.
-UPDATE_OPTIONS=-Pd
-# Use -P to prune empty directories.
-# Use -d to create any directories that exist in the repository but not
-#           locally.
-# Use -A to reset any sticky tags, dates, or `-k' options.
+# SVN command
+GCC_SVN=${GCC_SVN-${SVN-svn}}
+# Default options used when updating via SVN (none).
+UPDATE_OPTIONS=""
 
 ######## Anything below shouldn't be changed by regular users.
 
 # Arrange for the value of $0 to be available for functions
 self=$0
 
+# This function prints its arguments to standard output unless
+# "silent" is set.
+unset silent
+chat () {
+    if [ -z "$silent" ]; then
+        echo "$@"
+    fi
+}
+
 # This function prints a list of all generated files, along with their
 # dependencies.  Note that only one target is supported per line: the
 # colon is stripped from the output.
 files_and_dependencies () {
     sed -e 's/ *#.*//' -e '/^$/d' -e 's/://' <<\EOF
-# All automake dependencies within texinfo
-# In fact, not all, since we do not care about sub-directories that
-# we do not build.  In particular, *.po and *.gmo are not touched.
-texinfo/aclocal.m4: texinfo/configure.in texinfo/acinclude.m4
-texinfo/Makefile.in: texinfo/Makefile.am texinfo/configure.in texinfo/aclocal.m4
-texinfo/configure: texinfo/configure.in texinfo/aclocal.m4
-texinfo/stamp-h.in: texinfo/configure.in texinfo/aclocal.m4 texinfo/acconfig.h
-texinfo/lib/Makefile.in: texinfo/lib/Makefile.am texinfo/configure.in texinfo/aclocal.m4
-texinfo/makeinfo/Makefile.in: texinfo/makeinfo/Makefile.am texinfo/configure.in texinfo/aclocal.m4
-texinfo/util/Makefile.in: texinfo/util/Makefile.am texinfo/configure.in texinfo/aclocal.m4
+# fixincludes
+fixincludes/configure: fixincludes/configure.ac fixincludes/aclocal.m4
+fixincludes/config.h.in: fixincludes/configure.ac fixincludes/aclocal.m4
+# intl library
+intl/plural.c: intl/plural.y
+intl/configure: intl/configure.ac intl/aclocal.m4
+intl/config.h.in: intl/configure.ac intl/aclocal.m4
 # Now, proceed to gcc automatically generated files
-gcc/configure: gcc/configure.in
-gcc/cstamp-h.in: gcc/configure.in gcc/acconfig.h
+gcc/configure: gcc/configure.ac
+gcc/cstamp-h.in: gcc/configure.ac
 gcc/config.in: gcc/cstamp-h.in
 gcc/fixinc/fixincl.x: gcc/fixinc/fixincl.tpl gcc/fixinc/inclhack.def
-gcc/intl/plural.c: gcc/intl/plural.y
+gcc/config/arm/arm-tune.md: gcc/config/arm/arm-cores.def gcc/config/arm/gentune.sh
 # And then, language-specific files
-gcc/f/intdoc.texi: gcc/f/intdoc.in gcc/f/intdoc.c gcc/f/intrin.h gcc/f/intrin.def
 gcc/cp/cfns.h: gcc/cp/cfns.gperf
 gcc/java/keyword.h: gcc/java/keyword.gperf
-gcc/ada/treeprs.ads: gcc/ada/treeprs.adt gcc/ada/sinfo.ads gcc/ada/xtreeprs.adb
-gcc/ada/einfo.h: gcc/ada/einfo.ads gcc/ada/einfo.adb gcc/ada/xeinfo.adb
-gcc/ada/sinfo.h: gcc/ada/sinfo.ads gcc/ada/xsinfo.adb
-gcc/ada/nmake.adb: gcc/ada/sinfo.ads gcc/ada/nmake.adt gcc/ada/xnmake.adb
-gcc/ada/nmake.ads: gcc/ada/sinfo.ads gcc/ada/nmake.adt gcc/ada/xnmake.adb
-gcc/ada/gnat_ug_unx.texi: gcc/ada/gnat_ug.texi gcc/ada/xgnatug.adb gcc/ada/ug_words
-gcc/ada/gnat_ug_vms.texi: gcc/ada/gnat_ug.texi gcc/ada/xgnatug.adb gcc/ada/ug_words
-gcc/ada/gnat_ug_vxw.texi: gcc/ada/gnat_ug.texi gcc/ada/xgnatug.adb gcc/ada/ug_words
-gcc/ada/gnat_ug_w32.texi: gcc/ada/gnat_ug.texi gcc/ada/xgnatug.adb gcc/ada/ug_words
+# testsuite
+# Without this, _Pragma3.c can have a false negative.
+gcc/testsuite/gcc.dg/cpp/_Pragma3.c: gcc/testsuite/gcc.dg/cpp/mi1c.h
 # And libraries, at last
-libf2c/configure: libf2c/configure.in
-libf2c/libF77/configure: libf2c/libF77/configure.in
-libf2c/libI77/configure: libf2c/libI77/configure.in
-libf2c/libI77/stamp-h.in: libf2c/libI77/configure.in
-libf2c/libI77/config.h.in: libf2c/libI77/configure.in libf2c/libI77/stamp-h.in
-libf2c/libU77/configure: libf2c/libU77/configure.in
-libf2c/libU77/stamp-h.in: libf2c/libU77/configure.in libf2c/libU77/acconfig.h
-libobjc/configure: libobjc/configure.in
-# fastjar
-fastjar/aclocal.m4: fastjar/configure.in
-fastjar/Makefile.in: fastjar/Makefile.am fastjar/configure.in fastjar/aclocal.m4
-fastjar/configure: fastjar/configure.in fastjar/aclocal.m4
-fastjar/stamp-h.in: fastjar/configure.in fastjar/aclocal.m4
-boehm-gc/aclocal.m4: boehm-gc/configure.in boehm-gc/acinclude.m4
-boehm-gc/Makefile.in: boehm-gc/Makefile.am boehm-gc/configure.in boehm-gc/aclocal.m4
-boehm-gc/configure: boehm-gc/configure.in boehm-gc/aclocal.m4
-libjava/aclocal.m4: libjava/configure.in libjava/acinclude.m4
-libjava/Makefile.in: libjava/Makefile.am libjava/configure.in libjava/aclocal.m4
-libjava/configure: libjava/configure.in libjava/aclocal.m4
-libjava/libltdl/aclocal.m4: libjava/libltdl/configure.in libjava/libltdl/acinclude.m4
-libjava/libltdl/Makefile.in: libjava/libltdl/Makefile.am libjava/libltdl/configure.in libjava/libltdl/aclocal.m4
-libjava/libltdl/configure: libjava/libltdl/configure.in libjava/libltdl/aclocal.m4
-libjava/libltdl/stamp-h.in: libjava/libltdl/configure.in libjava/libltdl/aclocal.m4 libjava/libltdl/acconfig.h
+libbanshee/configure: libbanshee/configure.ac
+libmudflap/configure: libmudflap/configure.ac
+libobjc/configure: libobjc/configure.ac
+zlib/aclocal.m4: zlib/configure.ac zlib/acinclude.m4
+zlib/Makefile.in: zlib/Makefile.am zlib/configure.ac zlib/aclocal.m4
+zlib/configure: zlib/configure.ac zlib/aclocal.m4
+fastjar/aclocal.m4: fastjar/configure.ac
+fastjar/Makefile.in: fastjar/Makefile.am fastjar/configure.ac fastjar/aclocal.m4
+fastjar/configure: fastjar/configure.ac fastjar/aclocal.m4
+boehm-gc/aclocal.m4: boehm-gc/configure.ac
+boehm-gc/Makefile.in: boehm-gc/Makefile.am boehm-gc/configure.ac boehm-gc/aclocal.m4
+boehm-gc/configure: boehm-gc/configure.ac boehm-gc/aclocal.m4
+libada/configure: libada/configure.ac
+libffi/aclocal.m4: libffi/configure.ac libffi/acinclude.m4
+libffi/Makefile.in: libffi/Makefile.am libffi/configure.ac libffi/aclocal.m4
+libffi/configure: libffi/configure.ac libffi/aclocal.m4
+libffi/fficonfig.h.in: libffi/configure.ac libffi/aclocal.m4
+libgfortran/aclocal.m4: libgfortran/configure.ac libgfortran/acinclude.m4
+libgfortran/Makefile.in: libgfortran/Makefile.am libgfortran/configure.ac libgfortran/aclocal.m4
+libgfortran/configure: libgfortran/configure.ac libgfortran/aclocal.m4
+libjava/aclocal.m4: libjava/configure.ac
+libjava/Makefile.in: libjava/Makefile.am libjava/configure.ac libjava/aclocal.m4
+libjava/configure: libjava/configure.ac libjava/aclocal.m4
+libjava/libltdl/aclocal.m4: libjava/libltdl/configure.ac libjava/libltdl/acinclude.m4
+libjava/libltdl/Makefile.in: libjava/libltdl/Makefile.am libjava/libltdl/configure.ac libjava/libltdl/aclocal.m4
+libjava/libltdl/configure: libjava/libltdl/configure.ac libjava/libltdl/aclocal.m4
+libjava/libltdl/config-h.in: libjava/libltdl/configure.ac libjava/libltdl/aclocal.m4
+libcpp/aclocal.m4: libcpp/configure.ac
+libcpp/Makefile.in: libcpp/configure.ac libcpp/aclocal.m4
+libcpp/configure: libcpp/configure.ac libcpp/aclocal.m4
 # Top level
 Makefile.in: Makefile.tpl Makefile.def
+configure: configure.in config/acx.m4
 EOF
 }
 
@@ -125,10 +132,19 @@ touch_files () {
     echo ':' >> Makefile.$$
     echo '	@for f in $? $@; do test -f $$f || exit 0; done; \' >> Makefile.$$
     echo '	echo Touching $@...; \' >> Makefile.$$
-    echo '	echo Touching $@... 1>&2; \' >> Makefile.$$
+    chat '	echo Touching $@... 1>&2; \' >> Makefile.$$
     echo '	touch $@' >> Makefile.$$
     files_and_dependencies | sed 's,[^ ]* ,,;s,$, :,' >> Makefile.$$
-    while ${MAKE-make} -s -f Makefile.$$ all | grep . > /dev/null; do
+
+    # We would have to explicitly shut off the "Entering... Leaving..."
+    # messages through "--no-print-directory" to handle the case when
+    # we were called from a recursive invocation (i.e. "$(MAKE)" in a
+    # Makefile, not just make).  Passing only "-s" doesn't help then,
+    # because make has helpfully added "-w" to MAKEFLAGS automatically.
+    # Unfortunately we do not require GNU make other than for building
+    # and testing, so let's just grep known text explicitly echoed by
+    # the rule.
+    while ${MAKE-make} -s -f Makefile.$$ all | grep Touching > /dev/null; do
       sleep 1
     done 2>&1
     rm -f Makefile.$$
@@ -139,21 +155,21 @@ touch_files () {
 # this script.  By re-execing it, we ensure that the appropriate
 # dependencies and rules will be used.
 touch_files_reexec () {
-    echo "Adjusting file timestamps"
-    exec ${CONFIG_SHELL-/bin/sh} $self --touch
+    chat "Adjusting file timestamps"
+    exec ${CONFIG_SHELL-/bin/sh} $self ${silent+"--silent"} --touch
 }
 
 # This functions applies a patch to an existing tree.
 apply_patch () {
-    if [ -f $1 ]; then
+    if [ -f "$1" ]; then
 	echo "Applying patch file $1"
-	case "$1" in
+	case $1 in
 	*gz)
-	    gzip -d -c $1 | patch -p1 ;;
+	    gzip -d -c "$1" | patch -p1 ;;
 	*bz2)
-	    bzip2 -d -c $1 | patch -p1 ;;
+	    bzip2 -d -c "$1" | patch -p1 ;;
 	*)
-	    cat $1 | patch -p1 ;;
+	    patch -p1 < "$1";;
 	esac
     fi
     touch_files_reexec
@@ -164,6 +180,13 @@ if [ ! -f gcc/version.c ]; then
     echo "This does not seem to be a GCC tree!"
     exit
 fi
+
+case "$1" in
+--silent)
+    silent=t
+    shift
+    ;;
+esac
 
 case "$1" in
 # First of all, check whether we are going to process a patch.
@@ -206,9 +229,9 @@ p
 
 esac
 
-# Check whether this indeed looks like a local CVS tree.
-if [ ! -d CVS ]; then
-    echo "This does not seem to be a GCC CVS tree!"
+# Check whether this indeed looks like a local SVN tree.
+if [ ! -d .svn ]; then
+    echo "This does not seem to be a GCC SVN tree!"
     exit
 fi
 
@@ -219,16 +242,17 @@ else
     set -- $UPDATE_OPTIONS ${1+"$@"}
 fi
 
-echo "Updating CVS tree"
-cvs -q update ${1+"$@"}
+chat "Updating SVN tree"
+
+$GCC_SVN ${silent+-q}  --non-interactive update ${1+"$@"}
 if [ $? -ne 0 ]; then
     (touch_files_reexec)
-    echo "CVS update of full tree failed." >&2
+    echo "SVN update of full tree failed." >&2
     exit 1
 fi
 
 {
   date
-  TZ=UTC date
+  echo "`TZ=UTC date` (revision `svnversion .`)"
 } > LAST_UPDATED
 touch_files_reexec
diff --git a/gcc/gcc/po/exgettext b/gcc/gcc/po/exgettext
--- a/gcc/gcc/po/exgettext
+++ b/gcc/gcc/po/exgettext
@@ -1,22 +1,24 @@
 #! /bin/sh
 # Wrapper around gettext for programs using the msgid convention.
-# Copyright 1998, 2001, 2002 Free Software Foundation, Inc.
+# Copyright 1998, 2001, 2002, 2003 Free Software Foundation, Inc.
 
 # Written by Paul Eggert <eggert@twinsun.com>.
 # Revised by Zack Weinberg <zackw@stanford.edu> for no-POTFILES operation.
 
-# This program is free software; you can redistribute it and/or modify
+# This file is part of GCC.
+
+# GCC is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2, or (at your option)
 # any later version.
 
-# This program is distributed in the hope that it will be useful,
+# GCC is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 
 # You should have received a copy of the GNU General Public License
-# along with GNU CC; see the file COPYING.  If not, write to
+# along with GCC; see the file COPYING.  If not, write to
 # the Free Software Foundation, 59 Temple Place - Suite 330,
 # Boston, MA 02111-1307, USA.
 
@@ -41,6 +43,12 @@ xgettext=$1
 package=$2
 srcdir=$3
 
+case `$xgettext --version | sed -e 1q | sed -e 's/^\([^0-9]*\)//'` in
+  0.14.[5-9]* | 0.14.[1-9][0-9]* | 0.1[5-9]* | 0.[2-9][0-9]* | [1-9].*) : ;;
+  *) echo "$xgettext is too old.  GNU xgettext 0.14.5 is required"
+     exit 1 ;;
+esac
+
 nl='
 '
 
@@ -53,8 +61,15 @@ trap "rm -r $T" 0
 
 pwd=`${PWDCMD-pwd}`
 kopt=$pwd/$T/keyword-options
+kopt2=$pwd/$T/keyword2-options
 emsg=$pwd/$T/emsgids.c
 posr=$pwd/$T/po-sources
+pottmp1=$pwd/$T/tmp1.pot
+pottmp2=$pwd/$T/tmp2.pot
+pottmp=$pwd/$T/tmp.pot
+
+# Extra files to scan
+extra_files=$pwd/options.c
 
 # Locate files to scan, and generate the list.  All .c, .h, and .def files
 # in $srcdir are examined, likewise $srcdir/config and $srcdir/config/*
@@ -73,12 +88,14 @@ echo "scanning for keywords and %e strings..." >&2
 
 ( cd $srcdir
   lang_subdirs=`echo */config-lang.in | sed -e 's|config-lang\.in||g'`
-  for dir in "" config/ config/*/ $lang_subdirs
-  do  for glob in '*.c' '*.h' '*.def'
-      do  eval echo $dir$glob
-      done
-  done | tr ' ' "$nl" | grep -v '\*' |
-  $AWK -v excl=po/EXCLUDES -v posr=$posr -v kopt=$kopt -v emsg=$emsg '
+  { for dir in "" config/ config/*/ $lang_subdirs
+    do  for glob in '*.c' '*.h' '*.def'
+        do  eval echo $dir$glob
+        done
+    done;
+    echo $extra_files;
+  } | tr ' ' "$nl" | grep -v '\*' |
+  $AWK -v excl=po/EXCLUDES -v posr=$posr -v kopt=$kopt -v kopt2=$kopt2 -v emsg=$emsg '
 function keyword_option(line) {
     paren_index = index(line, "(")
     name = substr(line, 1, paren_index - 1)
@@ -92,12 +109,28 @@ function keyword_option(line) {
     for (n = 1; sub(/^[^,]*,/, "", args); n++) {
 	continue
     }
+    format=""
+    if (args ~ /g$/)
+    	format="gcc-internal-format"
+    else if (args ~ /c$/)
+    	format="c-format"
 
-    if (n == 1) { keyword = name }
-    else        { keyword = name ":" n }
+    if (n == 1) { keyword = "--keyword=" name }
+    else { keyword = "--keyword=" name ":" n }
+    if (format) {
+        keyword=keyword "\n--flag=" name ":" n ":" format
+    }
 
-    if (! keyword_seen[keyword]++) {
-	print "--keyword=" keyword > kopt
+    if (! keyword_seen[name]) {
+	if (format == "gcc-internal-format")
+		print keyword > kopt2
+	else
+		print keyword > kopt
+    	keyword_seen[name] = keyword
+    } else if (keyword_seen[name] != keyword) {
+	printf("%s used incompatibly as both %s and %s\n",
+	       name, keyword_seen[name], keyword)
+	exit (1)
     }
 }
 
@@ -105,18 +138,21 @@ function spec_error_string (line) {
     while ((percent_index = index(line, "%e")) != 0) {
 	escape = substr(line, percent_index - 1, 1)
 	line = substr(line, percent_index + 2)
-	if (escape == "%") return
+	if (escape == "%") continue
 
 	bracket_index = index(line, "}")
+	quote_index = index(line, "\"")
 	if (bracket_index == 0) return
+	if (quote_index != 0 && bracket_index > quote_index) return
 
 	msgid = substr(line, 1, bracket_index - 1)
-	if (index(msgid, "%") != 0) return
+	line = substr(line, bracket_index + 1)
+
+	if (index(msgid, "%") != 0) continue
 
 	printf("#line %d \"%s\"\n", lineno, file) > emsg
 	printf("_(\"%s\")\n", msgid) > emsg
 
-	line = substr(line, bracket_index + 1)
     }
 }
 
@@ -149,10 +185,24 @@ END {
     }
     print emsg > posr
 }'
-)
+) || exit
 
 # Run the xgettext command, with temporary added as a file to scan.
 echo "running xgettext..." >&2
 $xgettext --default-domain=$package --directory=$srcdir \
 	  --add-comments `cat $kopt` --files-from=$posr \
-	  --language=c -o po/$package.pot
+	  --copyright-holder="Free Software Foundation, Inc." \
+	  --msgid-bugs-address="http://gcc.gnu.org/bugs.html" \
+	  --language=c -o $pottmp1
+$xgettext --default-domain=$package --directory=$srcdir \
+	  --add-comments --keyword= `cat $kopt2` --files-from=$posr \
+	  --copyright-holder="Free Software Foundation, Inc." \
+	  --msgid-bugs-address="http://gcc.gnu.org/bugs.html" \
+	  --language=GCC-source -o $pottmp2
+$xgettext --default-domain=$package \
+	  --add-comments $pottmp1 $pottmp2 \
+	  --copyright-holder="Free Software Foundation, Inc." \
+	  --msgid-bugs-address="http://gcc.gnu.org/bugs.html" \
+	  --language=PO -o $pottmp
+# Remove local paths from .pot file.
+sed "s:$srcdir/::g;s:$pwd/::g;" <$pottmp >po/$package.pot
diff --git a/gccfast/build_gcc b/gccfast/build_gcc
--- a/gccfast/build_gcc
+++ b/gccfast/build_gcc
@@ -46,7 +46,17 @@ build_gcc_main()
       echo "The temporary directory '$TEMP' does not exist!"
       exit 1
     fi
-    
+
+    # Make sure that GCC 4 never gets used.
+    # <rdar://problem/4280487> Chardonnay: gccfast fails to build
+    rm -rf $TEMP/build_gcc.$$ && mkdir /tmp/build_gcc.$$ || exit 1
+    PATH=$TEMP/build_gcc.$$:$PATH
+    for FILE in gcc g++ cpp c++ gcov
+        do ln -s /usr/bin/$FILE-3.3 $TEMP/build_gcc.$$/$FILE
+        ln -s /usr/bin/$FILE-3.3 $TEMP/build_gcc.$$/$FILE-4.0
+    done
+    ln -s /usr/bin/gcc-3.3 $TEMP/build_gcc.$$/cc
+
     #
     # The host on which we are running on now (what machine is being used to build
     # compiler)...
@@ -66,7 +76,10 @@ build_gcc_main()
     # Name (and install_name!) of libstdc++.dylib to build (if any.)
     LIBSTDCPP_DYLIB=libstdc++.dylib
     LIBSTDCPP_DYLIB_VERSION=A
-    LIBRARIES="libgcc.a libcc_kext.a libgcc_static.a libsupc++.a $LIBSTDCPP_DYLIB libstdc++.a libcc_noc++.a"
+    # Name of libstdc++ with public instead of private extern symbols.
+    LIBSTDCPP_CLEAN=libstdc++_ZeroLink.a
+    # List of all libraries.
+    LIBRARIES="libgcc.a libcc_kext.a libgcc_static.a libsupc++.a $LIBSTDCPP_DYLIB $LIBSTDCPP_CLEAN libstdc++.a libcc_noc++.a"
     TOOLS="gcc$SUFFIX g++$SUFFIX c++$SUFFIX gcov$SUFFIX cpp$SUFFIX" # c++3 must be after g++3 in the list
     CRTS="crt2.o"
     RANLIB_FOR_TARGET=`whereis ranlib`
@@ -219,6 +232,8 @@ build_gcc_main()
     #
     # Install HTML documentation
     $nc install_html
+
+    rm -rf $TEMP/build_gcc.$$
 
     if [ ! "$n" ]; then
     	box_title "build_gcc script completed at `date +'%x %X %Z'`"
@@ -514,6 +529,7 @@ check_for_cross_compilers()
 #
 configure_gcc() 
 {
+    export CONFIG_SITE=$SRCROOT/config.apple
     for target in $TARGETS; do
 	for host in $HOSTS; do
 	    $n mkdir -p $OBJROOT/cc-$target-on-$host
@@ -545,6 +561,7 @@ configure_gcc()
 			     "Default cc      = `\cc -v 2>&1 | fgrep 'gcc version' | \
 						 sed -e 's/.*version \([^ ,]*\),.*version \([^ ]*\).*/version \2, \1/'`" \
 			     "Curr. hdrs      = `\ls -l /usr/include/gcc/darwin/default | sed -e 's,.*-> \(.*\),\1,'`" \
+			     "CONFIG_SITE     = $CONFIG_SITE" \
 			     "ENABLE_CHECKING = ${ENABLE_CHECKING:---enable-checking}"
 		$n rm -f make.id
 		$n echo $SRCROOT/gcc:$arch > make.id
@@ -568,11 +585,13 @@ configure_gcc()
 					  --enable-languages=$q"$ENABLE_LANGUAGES"$q \
 					  ${ENABLE_CHECKING:---enable-checking} \
 					  --prefix=$PREFIX \
+					  --with-headers \
 					  --enable-build-gcc
 		$SET +x
 	    fi
 	done
     done
+    unset CONFIG_SITE
 }
 
 #---------------------------------------------------------------------------#
@@ -761,6 +780,7 @@ build_compiler()
 					    else echo cc -arch $target -no-cpp-precomp; fi; \
 					else echo ./xgcc -B./ -no-cpp-precomp; fi`" \
 		       BISON=bison \
+		       BISON=/usr/local/bin/bison-1.28 \
 		       CFLAGS="$no_boot_opt_flag $OPT_OVERRIDE $CFLAGS" \
 		       GCC_CFLAGS="-no-cpp-precomp $CFLAGS" \
 		       BOOT_CFLAGS="${OPT_OVERRIDE:--O2} $CFLAGS -no-cpp-precomp -mdynamic-no-pic" \
@@ -1181,7 +1201,7 @@ build_libgcc()
 	    libname=libcc_kext.a
     	    extra_args="-static $extra_args"
     	    if [ "$target" = "ppc" ]; then
-    	    	extra_args="$extra_args -mlong-branch"
+    	    	extra_args="$extra_args -mlongcall"
     	    fi
     	    ;;
     	static)
@@ -1500,10 +1520,18 @@ install_fat()
 	for file in $LIBRARIES; do
 	    thin_files=
 	    for target in $TARGETS; do
+	        # libstdc++ should only be installed for ppc
+	        if echo "$file" | fgrep -q ++; then
+	            if [ $target != "ppc" ]; then continue; fi
+	        fi
 		if [ "$file" = "$LIBSTDCPP_DYLIB" ]; then
 		    # Keep a "clean" (non-nmedited) copy of libstdc++.a.
 		    thin_files="$thin_files $sym/$host/lib/$target/libstdc++.clean.a"
 		    fat_file="$fat/$privatelib/$file"
+                elif [ "$file" = "$LIBSTDCPP_CLEAN" ]; then
+                    # Create a "clean" fat libstdc++.a, for ZeroLink.
+                    thin_files="$thin_files $sym/$host/lib/$target/libstdc++.clean.a"
+                    fat_file="$fat/$lib/$file"
 		else
 		    thin_files="$thin_files $sym/$host/lib/$target/$file"
 		    # Change all global public data into private externs.
@@ -1717,9 +1745,25 @@ clean_gcc()
 # Install the HTML documentation
 install_html()
 {
+    HTMLDIR="$DSTROOT/Developer/ADC Reference Library/documentation/DeveloperTools"
     if [ -d $OBJROOT/cc-$buildhost-on-$buildhost/HTML ]; then
-	mkdir -p $DSTROOT/Developer/Documentation/DeveloperTools
-	cp -r $OBJROOT/cc-$buildhost-on-$buildhost/HTML/* $DSTROOT/Developer/Documentation/DeveloperTools
+	mkdir -p "$HTMLDIR"
+	cp -r $OBJROOT/cc-$buildhost-on-$buildhost/HTML/* "$HTMLDIR"
+    fi
+    # Install the libstdc++ documentation
+    if [ -d $SRCROOT/libstdc++-v3/docs/html/ ]; then
+	mkdir -p "$HTMLDIR/gcc-3.3/libstdc++"
+	libstdcxx_html_subdirs="17_intro 18_support 19_diagnostics 20_util 21_strings 22_locale 23_containers 24_iterators 25_algorithms 26_numerics 27_io ext faq"
+	cp $SRCROOT/libstdc++-v3/docs/html/*.html "$HTMLDIR/gcc-3.3/libstdc++"
+	if [ -r $SRCROOT/libstdc++-v3/docs/html/lib3styles.css ]; then
+	    cp $SRCROOT/libstdc++-v3/docs/html/lib3styles.css "$HTMLDIR/gcc-3.3/libstdc++"
+	fi
+	for libstdcxx_html_subdir in $libstdcxx_html_subdirs; do
+	    if [ -d $SRCROOT/libstdc++-v3/docs/html/$libstdcxx_html_subdir ]; then
+		mkdir -p "$HTMLDIR/gcc-3.3/libstdc++/$libstdcxx_html_subdir"
+		cp $SRCROOT/libstdc++-v3/docs/html/$libstdcxx_html_subdir/*.html "$HTMLDIR/gcc-3.3/libstdc++/$libstdcxx_html_subdir"
+	    fi
+	done
     fi
 }
 
diff --git a/ncurses/ncurses/misc/run_tic.in b/ncurses/ncurses/misc/run_tic.in
--- a/ncurses/ncurses/misc/run_tic.in
+++ b/ncurses/ncurses/misc/run_tic.in
@@ -1,6 +1,6 @@
 #!@SHELL@
 ##############################################################################
-# Copyright (c) 1998,2000 Free Software Foundation, Inc.                     #
+# Copyright (c) 1998-2004,2005 Free Software Foundation, Inc.                #
 #                                                                            #
 # Permission is hereby granted, free of charge, to any person obtaining a    #
 # copy of this software and associated documentation files (the "Software"), #
@@ -29,7 +29,7 @@
 #
 # Author: Thomas E. Dickey 1996,2000
 #
-# $Id: run_tic.in,v 1.1.1.1 2001/11/29 20:40:55 jevans Exp $
+# $Id: run_tic.in,v 1.20 2005/09/17 23:13:49 tom Exp $
 # This script is used to install terminfo.src using tic.  We use a script
 # because the path checking is too awkward to do in a makefile.
 #
@@ -54,6 +54,7 @@ echo '** Building terminfo database, please wait...'
 : ${LN_S="@LN_S@"}
 : ${THAT_CC=cc}
 : ${THIS_CC=cc}
+: ${ext_funcs=@NCURSES_EXT_FUNCS@}
 
 test -z "${DESTDIR}" && DESTDIR=
 
@@ -62,26 +63,34 @@ test -z "${DESTDIR}" && DESTDIR=
 # on the host's copy of tic to compile the terminfo database.
 if test "$THAT_CC" = "$THIS_CC" ; then
 case "$PATH" in
-:*) PATH=../progs:${DESTDIR}$bindir$PATH ;;
-*) PATH=../progs:${DESTDIR}$bindir:$PATH ;;
+:*) PATH=../progs:../lib:${DESTDIR}$bindir$PATH ;;
+*) PATH=../progs:../lib:${DESTDIR}$bindir:$PATH ;;
 esac
 export PATH
+SHLIB="sh $srcdir/shlib"
+else
+# Cross-compiling, so don't set PATH or run shlib.
+SHLIB=
+# reset $suffix, since it applies to the target, not the build platform.
+suffix=
 fi
 
-#
+
 # set another env var that doesn't get reset when `shlib' runs, so `shlib' uses
 # the PATH we just set.
-#
-NEWPATH=$PATH
-export NEWPATH
-PROG_BIN_DIR=${DESTDIR}$bindir
-export PROG_BIN_DIR
+SHLIB_PATH=$PATH
+export SHLIB_PATH
 
+# set a variable to simplify environment update in shlib
+SHLIB_HOST=@host_os@
+export SHLIB_HOST
+
+# don't use user's TERMINFO variable
 TERMINFO=${DESTDIR}$ticdir ; export TERMINFO
 umask 022
 
 # Construct the name of the old (obsolete) pathname, e.g., /usr/lib/terminfo.
-TICDIR=`echo $TERMINFO | sed -e 's@/share/@/lib/@'`
+TICDIR=`echo $TERMINFO | sed -e 's%/share/\([^/]*\)$%/lib/\1%'`
 
 # Remove the old terminfo stuff; we don't care if it existed before, and it
 # would generate a lot of confusing error messages if we tried to overwrite it.
@@ -89,64 +98,42 @@ TICDIR=`echo $TERMINFO | sed -e 's@/share/@/lib/@'`
 # the directory is actually a symbolic link.
 ( cd $TERMINFO && rm -fr ? 2>/dev/null )
 
-# If we're not installing into /usr/share/, we'll have to adjust the location
-# of the tabset files in terminfo.src (which are in a parallel directory).
-TABSET=`echo $ticdir | sed -e 's@/terminfo$@/tabset@'`
-if test "x$TABSET" != "x/usr/share/tabset" ; then
-	echo '** adjusting tabset paths'
-	TMP=${TMPDIR-/tmp}/$$
-	sed -e s:/usr/share/tabset:$TABSET:g $source >$TMP
-	trap "rm -f $TMP" 0 1 2 5 15
-	source=$TMP
-fi
-
+if test "$ext_funcs" = 1 ; then
 cat <<EOF
 Running tic to install $TERMINFO ...
 
-	You may see messages regarding unknown capabilities, e.g., AX.
-	These are extended terminal capabilities which can be compiled
+	You may see messages regarding extended capabilities, e.g., AX.
+	These are extended terminal capabilities which are compiled
 	using
 		tic -x
-	Read the INSTALL document before doing this - it can cause
-	problems for older ncurses applications.
+	If you have ncurses 4.2 applications, you should read the INSTALL
+	document, and install the terminfo without the -x option.
 
 EOF
-if ( $srcdir/shlib tic$suffix -s -o $TERMINFO $source )
+if ( $SHLIB tic$suffix -x -s -o $TERMINFO $source )
 then
 	echo '** built new '$TERMINFO
 else
 	echo '? tic could not build '$TERMINFO
 	exit 1
 fi
+else
+cat <<EOF
+Running tic to install $TERMINFO ...
 
-# Make a symbolic link to provide compatibility with applications that expect
-# to find terminfo under /usr/lib.  That is, we'll _try_ to do that.  Not
-# all systems support symbolic links, and those that do provide a variety
-# of options for 'test'.
-if test "$TICDIR" != "$TERMINFO" ; then
-	( rm -f $TICDIR 2>/dev/null )
-	if ( cd $TICDIR 2>/dev/null )
-	then
-		cd $TICDIR
-		TICDIR=`pwd`
-		if test $TICDIR != $TERMINFO ; then
-			# Well, we tried.  Some systems lie to us, so the
-			# installer will have to double-check.
-			echo "Verify if $TICDIR and $TERMINFO are the same."
-			echo "The new terminfo is in $TERMINFO; the other should be a link to it."
-			echo "Otherwise, remove $TICDIR and link it to $TERMINFO."
-		fi
-	else
-		cd ${DESTDIR}$prefix
-		# Construct a symbolic link that only assumes $ticdir has the
-		# same $prefix as the other installed directories.
-		RELATIVE=`echo $ticdir|sed -e 's:^'$prefix'/::'`
-		if test "$RELATIVE" != "$ticdir" ; then
-			RELATIVE=../`echo $ticdir|sed -e 's:^'$prefix'/::' -e 's:^/::'`
-		fi
-		if ( @LN_S@ $RELATIVE $TICDIR )
-		then
-			echo '** linked '$TICDIR' for compatibility'
-		fi
-	fi
+	You may see messages regarding unknown capabilities, e.g., AX.
+	These are extended terminal capabilities which may be compiled
+	using
+		tic -x
+	If you have ncurses 4.2 applications, you should read the INSTALL
+	document, and install the terminfo without the -x option.
+
+EOF
+if ( $SHLIB tic$suffix -s -o $TERMINFO $source )
+then
+	echo '** built new '$TERMINFO
+else
+	echo '? tic could not build '$TERMINFO
+	exit 1
+fi
 fi
diff --git a/postfix/postfix/conf/post-install b/postfix/postfix/conf/post-install
--- a/postfix/postfix/conf/post-install
+++ b/postfix/postfix/conf/post-install
@@ -158,6 +158,8 @@
 #	The group for mail submission and for queue management commands.
 #	Its numerical group ID must not be used by any other accounts on the
 #	system, not even by the mail_owner account.
+# .IP html_directory
+#	The directory for the Postfix HTML files.
 # .IP manpage_directory
 #	The directory for the Postfix on-line manual pages.
 # .IP sample_directory
@@ -201,6 +203,7 @@ USAGE="Usage: $0 [name=value] command
 # IFS=value setting permanent. But some broken standard allows it.
 
 create=; set_perms=; upgrade_perms=; upgrade_conf=; first_install_reminder=
+obsolete=; keep_list=;
 
 for arg
 do
@@ -253,8 +256,24 @@ test -f $config_directory/postfix-files || {
     exit 1
 }
 
+# SunOS5 fmt(1) truncates lines > 1000 characters.
+
+fake_fmt() {
+    sed '
+    :top
+	/^\(  *\)\([^ ][^ ]*\)  */{
+	    s//\1\2\
+\1/
+	    P
+	    D
+	    b top
+	}
+    ' | fmt
+}
+
 case `uname -s` in
 HP-UX*) FMT=cat;;
+SunOS*) FMT=fake_fmt;;
      *) FMT=fmt;;
 esac
 
@@ -285,7 +304,7 @@ grep setgid_group $config_directory/main.cf >/dev/null 2>&1 || {
 test -f $config_directory/main.cf && {
     for name in daemon_directory command_directory queue_directory mail_owner \
         setgid_group sendmail_path newaliases_path mailq_path \
-	manpage_directory sample_directory readme_directory
+	html_directory manpage_directory sample_directory readme_directory
     do
 	eval junk=\$$name
         case "$junk" in
@@ -308,8 +327,7 @@ case $setgid_group in
 esac
 
 for path in "$daemon_directory" "$command_directory" "$queue_directory" \
-    "$sendmail_path" "$newaliases_path" "$mailq_path" "$manpage_directory" \
-    "$sample_directory"
+    "$sendmail_path" "$newaliases_path" "$mailq_path" "$manpage_directory"
 do
    case "$path" in
    /*) ;;
@@ -317,7 +335,7 @@ do
    esac
 done
 
-for path in "$readme_directory"
+for path in "$html_directory" "$readme_directory"
 do
    case "$path" in
    /*) ;;
@@ -332,7 +350,7 @@ done
 missing=
 for name in daemon_directory command_directory queue_directory mail_owner \
     setgid_group sendmail_path newaliases_path mailq_path manpage_directory \
-    sample_directory readme_directory
+    readme_directory html_directory
 do
     eval test -n \"\$$name\" || missing="$missing $name"
 done
@@ -367,10 +385,10 @@ POSTCONF="$command_directory/postconf"
 override=
 for name in daemon_directory command_directory queue_directory mail_owner \
     setgid_group sendmail_path newaliases_path mailq_path manpage_directory \
-    sample_directory readme_directory
+    sample_directory readme_directory html_directory
 do
     eval test \"\$$name\" = \"`$POSTCONF -c $config_directory -h $name`\" || {
-# apple: B&I workaround: 	override=1
+	override=1
 	break
     }
 done
@@ -385,6 +403,7 @@ test -n "$override" && {
 	"sendmail_path = $sendmail_path" \
 	"mailq_path = $mailq_path" \
 	"newaliases_path = $newaliases_path" \
+	"html_directory = $html_directory" \
 	"manpage_directory = $manpage_directory" \
 	"sample_directory = $sample_directory" \
 	"readme_directory = $readme_directory" \
@@ -404,6 +423,12 @@ test -n "$create" && {
 	[$]*) ;;
 	   *) continue;;
 	esac
+	# Skip hard links and symbolic links.
+	case $type in
+	[hl]) continue;;
+	[df]) ;;
+	   *) echo unknown type $type for $path in $config_directory/postfix-files1>&2; exit 1;;
+	esac
 	# Expand $name, and canonicalize null fields.
 	for name in path owner group flags
 	do
@@ -422,6 +447,15 @@ test -n "$create" && {
 	case $flags in *u*) upgrade_flag=1;; *) upgrade_flag=;; esac
 	case $flags in *c*) create_flag=1;; *) create_flag=;; esac
 	case $flags in *r*) recursive="-R";; *) recursive=;; esac
+	case $flags in *o*) obsolete_flag=1;; *) obsolete_flag=;; esac
+	# Flag obsolete objects. XXX Solaris 2..9 does not have "test -e".
+	if [ -n "$obsolete_flag" ]
+	then
+	    test -r $path -a "$type" != "d" && obsolete="$obsolete $path"
+	    continue;
+	else
+	    keep_list="$keep_list $path"
+	fi
 	# Create missing directories with proper owner/group/mode settings.
 	if [ -n "$create" -a "$type" = "d" -a -n "$create_flag" -a ! -d "$path" ]
 	then
@@ -439,9 +473,16 @@ test -n "$create" && {
 	test -n "$set_permission" && {
 	    chown $recursive $owner $path || exit 1
 	    test -z "$group" || chgrp $recursive $group $path || exit 1
-	    chmod $mode $path || exit 1
+	    # Don't "chmod -R"; queue file status is encoded in mode bits.
+	    if [ "$type" = "d" -a -n "$recursive" ]
+	    then
+		find $path -type d -exec chmod $mode "{}" ";"
+	    else
+		chmod $mode $path
+	    fi || exit 1
 	}
     done
+    IFS="$BACKUP_IFS"
 }
 
 # Upgrade existing Postfix configuration files if necessary.
@@ -463,6 +504,38 @@ EOF
 	echo Editing $config_directory/master.cf, adding missing entry for flush service
 	cat >>$config_directory/master.cf <<EOF || exit 1
 flush     unix  -       -       n       1000?   0       flush
+EOF
+    }
+
+    # Add missing trace service to master.cf.
+
+    grep 'trace.*bounce' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for trace service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+trace	  unix	-	-	n	-	0	bounce
+EOF
+    }
+
+    # Add missing verify service to master.cf.
+
+    grep '^verify.*verify' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for verify service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+verify	  unix	-	-	n	-	1	verify
+EOF
+    }
+
+    # Fix verify service process limit.
+
+    grep '^verify.*[ 	]0[ 	]*verify' \
+	$config_directory/master.cf >/dev/null && {
+	    echo Editing $config_directory/master.cf, setting verify process limit to 1
+	    ed $config_directory/master.cf <<EOF || exit 1
+/^verify.*[ 	]0[ 	]*verify/
+s/\([ 	]\)0\([ 	]\)/\11\2/
+p
+w
+q
 EOF
     }
 
@@ -497,22 +570,13 @@ EOF
 	}
     done
 
-    # With 20000 active queue files, the active queue directory should
-    # be hashed, and so should the other directories, because they
-    # can contain even more mail.
-    #
-    # Unfortunately, this sucks mailq performance on unloaded systems.
-    #
-    # If you don't want slow mailq, be sure to hash defer and deferred,
-    # because those two directories can contain lots of files.
+    # File systems have improved since Postfix came out, and all we
+    # require now is that defer and deferred are hashed because those
+    # can contain lots of files.
 
     found=`$POSTCONF -c $config_directory -h hash_queue_names`
     missing=
-    (echo "$found" | grep active >/dev/null) || missing="$missing active"
-    (echo "$found" | grep bounce >/dev/null) || missing="$missing bounce"
     (echo "$found" | grep defer >/dev/null)  || missing="$missing defer"
-    (echo "$found" | grep flush >/dev/null)  || missing="$missing flush"
-    (echo "$found" | grep incoming>/dev/null)|| missing="$missing incoming"
     (echo "$found" | grep deferred>/dev/null)|| missing="$missing deferred"
     test -n "$missing" && {
 	echo fixing main.cf hash_queue_names for missing $missing
@@ -523,23 +587,88 @@ EOF
     # Turn on safety nets for new features that could bounce mail that
     # would be accepted by a previous Postfix version.
 
-    unknown_local=unknown_local_recipient_reject_code
-    has_lrm=`$POSTCONF -n local_recipient_maps`
-    has_lrjc=`$POSTCONF -n $unknown_local`
-
-    if [ -z "$has_lrm" -a -z "$has_lrjc" ]
-    then
-	echo SAFETY: editing main.cf, setting $unknown_local=450.
-	echo See the RELEASE_NOTES and LOCAL_RECIPIENT_README files for details.
-	$POSTCONF -e "$unknown_local = 450" || exit 1
-    fi
+    # [The "unknown_local_recipient_reject_code = 450" safety net,
+    # introduced with Postfix 2.0 and deleted after Postfix 2.3.]
 
     # Add missing proxymap service to master.cf.
 
     grep '^proxymap.*proxymap' $config_directory/master.cf >/dev/null || {
 	echo Editing $config_directory/master.cf, adding missing entry for proxymap service
 	cat >>$config_directory/master.cf <<EOF || exit 1
-proxymap  unix        -       -       n       -       -       proxymap
+proxymap  unix	-	-	n	-	-	proxymap
+EOF
+    }
+
+    # Add missing anvil service to master.cf.
+
+    grep '^anvil.*anvil' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for anvil service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+anvil	  unix	-	-	n	-	1	anvil
+EOF
+    }
+
+    # Add missing scache service to master.cf.
+
+    grep '^scache.*scache' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for scache service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+scache	  unix	-	-	n	-	1	scache
+EOF
+    }
+
+    # Add missing discard service to master.cf.
+
+    grep '^discard.*discard' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for discard service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+discard	  unix	-	-	n	-	-	discard
+EOF
+    }
+
+    # Update the tlsmgr fifo->unix service.
+
+    grep "^tlsmgr[ 	]*fifo[ 	]" \
+	$config_directory/master.cf >/dev/null && {
+	    echo Editing $config_directory/master.cf, updating the tlsmgr from fifo to unix service
+	    ed $config_directory/master.cf <<EOF || exit 1
+/^tlsmgr[ 	]*fifo[ 	]/
+s/fifo/unix/
+s/[0-9][0-9]*/&?/
+p
+w
+q
+EOF
+    }
+
+    # Add missing tlsmgr service to master.cf.
+
+    grep '^tlsmgr.*tlsmgr' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for tlsmgr service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+tlsmgr    unix  -       -       n       1000?   1       tlsmgr
+EOF
+    }
+
+    # Add missing retry service to master.cf.
+
+    grep '^retry.*error' $config_directory/master.cf >/dev/null || {
+	echo Editing $config_directory/master.cf, adding missing entry for retry service
+	cat >>$config_directory/master.cf <<EOF || exit 1
+retry     unix  -       -       n       -       -       error
+EOF
+    }
+
+    # Report (but do not remove) obsolete files.
+
+    test -n "$obsolete" && {
+	cat <<EOF | ${FMT}
+
+    Note: the following files or directories still exist but are
+    no longer part of Postfix:
+
+    $obsolete
+
 EOF
     }
 
@@ -549,15 +678,16 @@ EOF
 
 test -n "$first_install_reminder" && {
 
-    ALIASES=`$POSTCONF -h alias_database | sed 's/^[^:]*://'`
-    NEWALIASES_PATH=`$POSTCONF -h newaliases_path`
+    ALIASES=`$POSTCONF -c $config_directory -h alias_database | sed 's/^[^:]*://'`
+    NEWALIASES_PATH=`$POSTCONF -c $config_directory -h newaliases_path`
     cat <<EOF | ${FMT}
 
     Warning: you still need to edit myorigin/mydestination/mynetworks
     parameter settings in $config_directory/main.cf.
 
-    See also http://www.postfix.org/faq.html for information about
-    dialup sites or about sites inside a firewalled network.
+    See also http://www.postfix.org/STANDARD_CONFIGURATION_README.html
+    for information about dialup sites or about sites inside a
+    firewalled network.
 
     BTW: Check your $ALIASES file and be sure to set up aliases
     that send mail for root and postmaster to a real person, then
